workspace:
  base: /app
  path: app/

pipeline:

  publish_docker:
     image: plugins/docker
     repo: sokoow/drone-kubectl-helm-clientcert
     secrets: [ docker_username, docker_password ]
     tags: [ ${DRONE_BUILD_NUMBER}, latest ]
